# clear working environment
rm(list = ls())

# lets get started with rvest

#libraries
pacman::p_load(tidyverse, rvest, XML, RCurl, rlist, datapasta, Hmisc)

url = "https://www.metal-archives.com/lists/A"

#xpath = #//*[@id="bandListAlpha"]/tbody/tr[1]/td[1]/a


source <- readLines(url, encoding = "UTF-8")

parsed_doc <- htmlParse(source, encoding = "UTF-8")

xpathSApply(parsed_doc, path = '/html/body/div/div[3]/div[2]/div/div/div[5]/table/tbody', xmlValue)



library(xml2)
webpage_url <- "https://www.metal-archives.com/lists/A"

webpage <- xml2::read_html(webpage_url)

ExOffndrsRaw <- rvest::html_table(webpage)[[1]] %>% 
  tibble::as_tibble(.name_repair = "unique") # repair the repeated columns
ExOffndrsRaw %>% dplyr::glimpse(45)




bands <- url %>%
  read_html() %>%
  html_nodes('.sorting_1') %>%
  html_table()
head(bands)





url <- "http://modules.ussquash.com/ssm/pages/leagues/list_scorecard.asp?id=105252"
page <- url %>%
  read_html()
table <- page %>% html_nodes(xpath='//*[@id="corebody"]/table[4]')
cells <- table %>% 
  html_nodes(xpath='.//td[not(@class="Line")]') %>% 
  html_text()
headers <- table %>% 
  html_nodes(xpath='.//th') %>% 
  html_text()

Ncol <- 8
rows <- sapply(split(cells, rep(1:(length(cells)/Ncol), each=Ncol)), paste, collapse="\t")
dd <- read.table(text=rows, header=F, sep="\t", col.names = headers)
head(dd)



df_1 = data.frame(
  stringsAsFactors = FALSE,
              Band = c("Band","A // Solution",
                       "A 12 Gauge Tragedy","A B I S M O","A Balance of Power",
                       "A Band of Orcs","A Baptism by Fire","A Bastard's Breath",
                       "A Belt Above Black","A Billion Limbs",
                       "A Binding Spirit","A Blackened Sight","A Blind Beggar",
                       "A Blind Prophecy","A Bloody Chasm","A Bloody Epitaph",
                       "A Body Falls","A Breach of Silence","A Break in the Storm",
                       "A Breath Before Surfacing","A Bribe for the Ferryman",
                       "A Broken Machine","A Brooding Body","A Brutal Confession",
                       "A Burial at Sea","A Buried Existence","A Call to Arms",
                       "A Canorous Quintet","A Caress of Twilight",
                       "A Circle of Crows","A City Screams in Terror","A Clockwork Opera",
                       "A Cloud Forest","A Cold Dead Body","A Cold Demise",
                       "A Cold Reality","A Cold Sun",
                       "A Collection of Cyclops Skulls","A Colour Cold Black",
                       "A Comfortable Way to Rot","A Concrete Lifeline","A Congregation of Horns",
                       "A Constant Battle","A Constant Storm","A Cosmic Trail",
                       "A Crack Baby Dead","A Crack in Time",
                       "A Crime of Passion","A Critical Mass","A Cursed Spirit in the Mirror",
                       "A Dance in Yellow","A Dank Season","A Dark Halo",
                       "A Dark Performance","A Dark Place","A Dark Thought",
                       "A Darkened Sea","A Dawn Serene","A Dawn Within",
                       "A Day in Venice","A Day of Pigs","A Day of Violence",
                       "A Day to Fall","A Day to Fall","A Day Worth Dying For",
                       "A Dead Calling","A Dead Cold Lament","A Dead End Society",
                       "A Dead God...","A Dead Lament","A Dead Silence",
                       "A Death by the Seaside","A Death for Every Sin","A Deathwish",
                       "A Deeper Dark","A Deeper Dreed","A Descent in Graves",
                       "A Devil's Daydream","A Devilish Domain","A Diaboli",
                       "A Diadem of Dead Stars","A Distant Sun",
                       "A Distorted Utopia","A Document Says","A Dream of Poe",
                       "A Dream Set Fire","A Dying God","A Dying Season",
                       "A Failing Devotion","A Fallen Martyr","A Fallen Theory",
                       "A Fear Called Treason","A Few Moments to Death",
                       "A Few Seasons Later","A Fight Called Hope","A Fitting Revenge",
                       "A Flock Named Murder","A Flourishing Scourge",
                       "A Fluorescent Finish","A Fonds Perdu","A Fool's Mockery",
                       "A Foot in the Grave","A Forest","A Forest of Dreams",
                       "A Forest of Stars","A Formula Controlled Emotion","A Ghastly Menace",
                       "A Ghost Named Alice","A Gift Called Anger",
                       "A Goat as Our Shepherd","A God from the Machine",
                       "A God or an Other","A Good Day for Killing","A Gram Trip",
                       "A Grave Calling","A Grave for Small Birds","A Greed Science",
                       "A Grim Saga","A Gruesome Find","A Hanging",
                       "A Haunted Mantra","A Hellish Digest","A Hero for the World",
                       "A Hill to Die Upon","A Hitman's Business","A Hope of Life",
                       "A Horse Called War","A House Cursed",
                       "A Human Costume","A II R","A Joker and His Gun",
                       "A Kid Hereafter in the Grinding Light","A Kill a Tem","A Knot of Tongues",
                       "A Land Beyond the Sea","A Lapse of Ethos",
                       "A Legend Falls","A Lesson in Violence","A Letter from Drowner",
                       "A Lie Nation","A Life Less Alive","A Life Once Lost",
                       "A Light in the Dark","A Limbo of Insanity","A Limine",
                       "A Little Beauty","A Little Magic","A Living Burden",
                       "A Living Sacrifice","A Loathing Requiem",
                       "A Lone Variant","A Long Forgotten Power","A Losing Season",
                       "A Lost Humanity","A Love Ends Suicide",
                       "A Lovely Day for Bloodshed","A Lower Deep","A Man a Wolf a Killer",
                       "A Man Named Onigumo","A Mátar","A Mental Disorder",
                       "A Million Dead Birds Laughing","A Million Evil Faces",
                       "A Million Miles","A Mind Confused","A Mind Traveller",
                       "A Misery Memoir","A Monumental Black Statue",
                       "A Morbid Masquerade","A Mors et Bello",
                       "A Mother Engulfed in 3 Characters","A Motive Inhumane","A Mournful Path",
                       "A Mourning Star","A Murder Confession","A Murder of Crows",
                       "A Murderer's Thought","A Mutilated Mind",
                       "A Nail Through the Urethra","A Naked Soul","A Nameless Dread","A New Dawn",
                       "A New Machine","A Night at the Chalet",
                       "A Night in the Abyss","A Novelist","A Nuestra Manera",
                       "A Pale December","A Pale Horse Named Death","A Peaceful Chaos",
                       "A Perfect Murder","A Perpetual Dying Mirror",
                       "A Persuasive Reason","A Piece for You to Bury",
                       "A Piece of Orpheus","A Pinga e o Diabo","A Place for Murder","A Plague",
                       "A Plague in Faith","A Plumbers Nightmare",
                       "A Pocket Sized Sun","A Portrait of Flesh and Blood",
                       "A Pregnant Light","A Premonition","A Pretext to Human Suffering",
                       "A Prison Called Earth","A Psychic Opera","A Punto",
                       "A Pyrrhic Victory","A Ravens Forest","A Red Dawn",
                       "A Red Nightmare","A Refraction","À Répit",
                       "A Retch of Blood","A Rose Dying in the Rain","A Sable Opiate",
                       "A Sad Bada","A Sailor's Grave","A Scapegoat's Faith",
                       "A Scar for the Wicked","A Sea of Silent Skulls",
                       "A Season in Hell","A Second of Silence","A Secret Ending",
                       "A Sense of Gravity","A Serious Day","A Serpent's Hand",
                       "A Shattered Dream","A Shattered Reflection",
                       "A Shed for the Dead","A Sickness Called Conscious",
                       "A Sickness unto Death","A Silent Ascent","A Silent Daylight",
                       "A Sin for a Prayer","A Skin for Dancing In","A Sleepless Malice",
                       "A Solemn Death","A Somber","A Sorrowful Dream",
                       "A Soul Called Perdition","A Sound of Thunder",
                       "A Squandered Potential","A Storm of Light",
                       "A Subtle Understatement","A Sun Traverse","A Switch Below","A Taste of Fear",
                       "A Taste of Freedom","A Tear Beyond",
                       "A Tempered Heart","A Templar's Burden","A Temple of Mirrors",
                       "A Temporal Causality","À Terre","A Terrible Night for a Curse",
                       "A Texas Funeral","A Theory on Conquest",
                       "A Thought Unleashed","A Thousand Buried Infants","A Thousand Dead",
                       "A Thousand Knives of Fire","A Thousand Reasons",
                       "A Thousand Shall Fall","A Thousand Shields",
                       "A Thousand Sufferings","A Thousand Times Repent","A Thousand Winters",
                       "A Thousand Years Slavery","A Threat to the Enemy",
                       "A Tomba Oberta","A Tortured Soul","A Total Wall",
                       "A Trail of Horror","A Traitor like Judas",
                       "A Transparent Lie","A Transylvanian Funeral","A Tree","A Tree of Signs",
                       "A Tribute to the Plague","A Trigger to Forget",
                       "A tu Puta Kara","A Very Old Ghost Behind the Farm",
                       "A Very Sad Story","A Village in Despair","A Vintage Death",
                       "A Virgin Burial","A Vision Grotesque",
                       "A Visperas de mi Muerte","A Void Eternal","A Vulgar Picture",
                       "A Waking Nightmare","A Walk Through Peril",
                       "A Walk with the Wicked","A Waste of Talent","A Well Thought Tragedy",
                       "A Westward March","A Winter Lost","A Winter Within",
                       "A Witness to the Slaughter","A World of Illness",
                       "A World of Lies","A World Without","A Worse Case Scenario",
                       "A Written Apology","A Young Man's Funeral","A-51","A-Bomb",
                       "A-Bros","A-I-E-A","A-II-Z","A-morality",
                       "A-Quarter","A-Rise","A-Team","A-Tierra","A:S:","A. Lostfield",
                       "A. R. Berdiales","A.A.S.","A.B.E.A.","A.B.L.",
                       "A.B.M.S. 696","A.C.E.","A.C.O.A.","A.C.O.V.S.U.R.",
                       "A.C.P.","A.C.S.","A.D","A.D. 4","A.D. Massacre",
                       "A.D.H.E.R.","A.D.N","A.D.N.","A.D.P.","A.Death.Experience",
                       "A.G.E","A.G.E.S.","A.G.R.E.S.O.R.","A.H.P.",
                       "A.I.D.S.","A.I.T.H.","A.K.A.","A.K.U","A.L.E.","A.L.M.A.",
                       "A.L.M.A.S.","A.L.P.","A.M.","A.M.E.S.","A.M.F.",
                       "A.M.P.","A.M.Q.A.","A.M.S.G.","A.N.A.E.L.","A.N.D.",
                       "A.N.I.M.A.L.","A.N.T.I.","A.N.T.I.L.I.V.","A.O.D.",
                       "A.P.O.D.","A.R.:.O.:.A.A","A.R.G.","A.R.M.A.","A.R.O.",
                       "A.S.A.H","A.S.A.R.R","A.S.D.","A.S.M.O.",
                       "A.S.U.R.A","A.T.O.N.","A.T.T.","A.TAXET.A","A.U.X.","A.V.D.L",
                       "A.V.I.S.","A.W.A.S.","The A.X.E. Project","A'tak",
                       "A((wake))","A*Teem","A/Oratos","A+","A|symmetry",
                       "A2Z","A5","AAA",
                       "Aaaaargh! Bloody 2-Handed Chainaxe Blow","Aaarghhh","Aabsinthe","Aabsynthum","Aaching",
                       "Aad Sleck","Aaen Anima","Aag","Aahas","Aäkon Këëtrëh",
                       "Aal","Aaltar","Aamon","Aamon","Aamonhammer",
                       "Aamunkajo","Aamutähti","Aanal Beehemoth","Äänipää",
                       "Ääniportti","Aanomm","Aanyl Pane","Aara","Aaranith",
                       "Aarcon","Aardoz","Aardvarks","Aarghh","Aarimest","Ääriö",
                       "Aarkanne","Aarmaroth Nathrath","Aarni","Aarnihauta",
                       "Aaron","Aaron Holt","Aaron Mortician","Aaron Pearson",
                       "Aaron Prevails","Aaronsrod","Aarseth","Aarson",
                       "Aasdgoihasdghexekul","Aasfauna","Aasfresser","Aasgard",
                       "Aasimon","Aaskereia","Aaskrähe","Aastraal","Aastyra",
                       "Aasverus","Aathma","Aatrox","Aatteet",
                       "Aauatlan Tliltik","Aavah","Aavas","Aazed","Aäzylium",
                       "Ab Aeterno","Ab Aeterno","Ab Eterno","Ab Imo Pectore",
                       "Ab Noctem","Ab Occulto","Ab-Irato","Ab-sense","Ab:Norm",
                       "Ab·est","Abaasy","Ababil","ABACABB","Abacinate",
                       "Abacinate","Abacination","Abacination","Abacination",
                       "Abacinator","Abadden","Abaddon","Abaddon","Abaddon",
                       "Abaddon","Abaddon","Abaddon","Abaddon","Abaddon",
                       "Abaddon","Abaddon","Abaddon","Abaddon","Abaddon",
                       "Abaddon","Abaddon","Abaddon","Abaddon","Abaddon","Abaddon",
                       "Abaddon","Abaddon","Abaddon","Abaddon","Abaddon",
                       "Abaddon","Abaddon","Abaddon","Abaddon","Abaddon",
                       "Abaddon","Abaddon","Abaddon","Abaddon"),
           Country = c("Country","United States",
                       "United States","Brazil","United States","United States",
                       "Canada","United States","United States",
                       "United Kingdom","Germany","Spain","Colombia","United States",
                       "United States","United States","United States",
                       "Australia","United States","United States","United Kingdom",
                       "United States","International","United States",
                       "Norway","Italy","United States","Sweden","Poland",
                       "United States","United States","United Kingdom",
                       "United States","Italy","Morocco","United States","Italy",
                       "United States","Germany","New Zealand","Canada",
                       "United Kingdom","United States","Portugal","Germany",
                       "United Kingdom","Greece","United States","United Kingdom",
                       "United States","Germany","United States","United States",
                       "Bolivia","Australia","Mexico","United States",
                       "Germany","United States","Italy","United States",
                       "United States","Argentina","United States","United States",
                       "United States","Chile","Germany","United States",
                       "Germany","Australia","United States","Canada","Bolivia",
                       "United States","United Kingdom","Belgium",
                       "United States","Japan","Norway","Greece","Ireland",
                       "United Kingdom","Germany","Portugal","United States",
                       "United Kingdom","Mexico","France","United States",
                       "Australia","Germany","Russia","France","Germany",
                       "United States","Canada","United States","United States",
                       "Austria","United Kingdom","Italy","Italy","Portugal",
                       "United Kingdom","Germany","United States","Austria",
                       "Germany","Belgium","United States","United States",
                       "Thailand","Croatia","United States","United States",
                       "Australia","United States","United States","United States",
                       "United States","Greece","Philippines","United States",
                       "Canada","Chile","United Kingdom","United States",
                       "United States","Italy","Australia","Denmark",
                       "Germany","Croatia","Finland","United States","Canada",
                       "United States","Russia","Finland","United States",
                       "United States","Russia","Bolivia","Mexico","Latvia",
                       "Japan","United States","United States","United States",
                       "Portugal","United States","Hungary","Mexico",
                       "United States","United States","United States","Austria",
                       "United States","Bolivia","United States","Australia",
                       "Malaysia","Germany","Sweden","Russia","United States",
                       "Italy","United States","Mexico","Finland","Cyprus",
                       "Australia","Canada","Colombia","Australia",
                       "United Kingdom","United States","Italy","Mexico",
                       "South Africa","Netherlands","Canada","United States",
                       "United Kingdom","United States","Argentina","Italy",
                       "United States","Portugal","Canada","Mexico","United States",
                       "Sweden","Netherlands","Brazil","Italy","Brazil",
                       "United States","Germany","Germany","United States",
                       "United States","Argentina","International","France",
                       "Germany","Argentina","United States","Canada","Australia",
                       "Brazil","Moldova","Italy","United Kingdom","Mexico",
                       "Germany","Chile","Germany","United States","Canada",
                       "United States","Brazil","Mexico","Lithuania",
                       "United States","Italy","United States","United States",
                       "United States","Norway","United States","Germany",
                       "United States","Argentina","Canada","United States",
                       "United States","Australia","Portugal","Brazil","Finland",
                       "United States","United States","United States",
                       "France","Denmark","Belgium","Italy","France","Italy",
                       "Spain","Sweden","United States","United States",
                       "France","United States","United States","United States",
                       "Germany","United States","United States",
                       "United States","Italy","United States","United States","Belgium",
                       "United States","Italy","Switzerland","United States",
                       "Spain","United States","Italy","Belgium","Germany",
                       "United Kingdom","United States","Italy","Portugal",
                       "Brazil","Brazil","Spain","France","France",
                       "Sri Lanka","Italy","Italy","United States","Colombia",
                       "Greece","United Kingdom","United States","Germany",
                       "South Africa","Norway","United States","Japan","Canada",
                       "Norway","Australia","Canada","United States",
                       "United States","United States","United Kingdom","Russia",
                       "Russia","Sweden","Sweden","Greece","United Kingdom",
                       "Russia","Korea, South","Germany","Germany",
                       "Argentina","Italy","Colombia","Spain","Spain","Turkey",
                       "Greece","Singapore","Germany","Canada","Russia",
                       "United States","Germany","Spain","United States","Australia",
                       "Argentina","Argentina","Spain","Australia",
                       "Germany","Japan","United States","Argentina","Norway",
                       "United States","Japan","United States","United States",
                       "Italy","Argentina","Argentina","Sweden","Finland",
                       "Germany","Hungary","Spain","United States","Canada",
                       "France","United Kingdom","Argentina","Latvia",
                       "Brazil","Finland","France","United Kingdom","Finland",
                       "Italy","Venezuela","International","Malaysia",
                       "United States","Netherlands","United States","Italy","Italy",
                       "United States","Czechia","Japan","Finland","Germany",
                       "Bulgaria","Poland","United States","Sweden",
                       "France","Czechia","Serbia","Finland","Czechia",
                       "Argentina","France","Indonesia","France","Romania",
                       "United States","United Kingdom","Czechia","Russia","Austria",
                       "France","Lithuania","United States","Italy",
                       "Romania","Brazil","Finland","Finland","Finland",
                       "International","Finland","Spain","United States","Switzerland",
                       "Germany","Germany","Italy","Germany",
                       "United States","Canada","Finland","Chile","Romania","Finland",
                       "Finland","Argentina","United States","United States",
                       "United States","United States","United States",
                       "United States","United States","Australia","Germany",
                       "Germany","Greece","Brazil","Germany","Germany",
                       "Netherlands","Canada","Brazil","Spain","Ecuador","Finland",
                       "Mexico","Brazil","Germany","Canada","France",
                       "Argentina","United States","Guatemala","Portugal","Italy",
                       "Switzerland","Argentina","Greece","Germany",
                       "Germany","United States","Indonesia","United States",
                       "Netherlands","United States","Belgium","Iceland",
                       "Australia","United States","United Kingdom","Greece",
                       "Honduras","South Africa","Bulgaria","Serbia","Mexico",
                       "Brazil","Australia","Trinidad and Tobago","Colombia",
                       "United States","United States","United States",
                       "United States","United States","Germany","Cuba","United States",
                       "India","Brazil","Indonesia","Argentina","Czechia",
                       "Australia","Venezuela","Chile","United States",
                       "Guatemala","Poland","Colombia","Colombia","Czechia",
                       "Poland"),
             Genre = c("Genre",
                       "Crust Punk/Thrash Metal","Deathcore","Doom/Stoner Metal",
                       "Melodic Death Metal/Metalcore","Death/Thrash Metal",
                       "Progressive Power Metal","Raw Black Metal","Melodic Death Metal/Metalcore",
                       "Groove Metal/Deathcore","Black Metal/Dark Ambient",
                       "Metalcore","Metalcore","Melodic/Progressive Metal",
                       "Heavy Metal/Grunge","Deathcore","Melodic Death Metal",
                       "Melodic Death Metal/Metalcore","Metalcore","Deathcore",
                       "Thrash/Groove Metal","Metalcore",
                       "Depressive Black Metal","Thrash Metal","Melodic Death Metal/Metalcore",
                       "Technical Death Metal/Metalcore","Thrash/Speed Metal",
                       "Melodic Death Metal","Black Metal/Ambient",
                       "Melodic Black/Death Metal","Deathcore","Symphonic Metal",
                       "Black Metal","Progressive Sludge Metal/Post-Hardcore",
                       "Black Metal/Ambient","Thrash/Death Metal",
                       "Depressive Black Metal","Doom/Sludge Metal",
                       "Thrash/Doom/Death Metal (early); Thrash/Alternative/Industrial Metal (later)",
                       "Progressive Death Metal","Heavy Metal/Hard Rock","Black Metal",
                       "Thrash/Progressive Metal",
                       "Melodic Death/Black Metal, Gothic Metal/Rock","Progressive Metal",
                       "Black Metal/Grindcore","Melodic Death/Progressive Metal",
                       "Progressive Death Metal/Deathcore","Thrash Metal","Black Metal",
                       "Experimental/Melodic Death Metal",
                       "Southern/Thrash/Groove Metal","Industrial/Thrash/Groove Metal",
                       "Melodic Gothic Metal","Death Metal","Depressive Black Metal",
                       "Black/Doom Metal","Doom Metal",
                       "Progressive Melodic Death Metal/Metalcore","Gothic/Doom Metal","Sludge Metal",
                       "Deathcore","Groove Metal/Metalcore",
                       "Melodic Death/Thrash Metal","Melodic Death Metal/Deathcore","Deathcore",
                       "Funeral Doom Metal","Melodic Death Metal/Metalcore",
                       "Melodic Black Metal","Melodic Death Metal/Metalcore",
                       "Technical Deathcore","Atmospheric Funeral Doom/Post-Metal",
                       "Death Metal/Hardcore","Blackened Death Metal",
                       "Thrash Metal/Hardcore","Heavy Metal",
                       "Progressive Death/Groove Metal/Deathcore","Melodic Black/Death Metal",
                       "Melodic Death Metal/Metalcore","Black Metal",
                       "Atmospheric Black Metal","Atmospheric Black/Doom Metal",
                       "Technical Melodic Death Metal","Experimental/Sludge Metal",
                       "Gothic/Doom Metal","Groove/Thrash Metal","Black Metal/Grindcore",
                       "Death Metal","Melodic Death Metal/Metalcore",
                       "Thrash/Groove Metal","Deathcore","Melodic Death Metal",
                       "Melodic Death Metal","Progressive Metal/Rock",
                       "Metalcore/Melodic Death Metal","Melodic Death Metal/Metalcore",
                       "Black/Death/Post-Metal","Progressive Black/Death Metal",
                       "Black Metal","Gothic Metal","Progressive Rock/Metal",
                       "Thrash/Death Metal","Black Metal",
                       "Atmospheric Black Metal/Ambient","Avant-garde/Progressive Black Metal",
                       "Death/Thrash Metal","Noise (early); Metalcore (later)",
                       "Progressive Power Metal","Metalcore/Thrash Metal",
                       "Death Metal","Progressive Black Metal",
                       "Atmospheric Post-Black Metal","Brutal Death Metal","Stoner/Doom/Sludge Metal",
                       "Progressive Death Metal/Deathcore",
                       "Melodic Post-Black Metal","Death Metal","Sludge Metal",
                       "Black/Death Metal","Thrash Metal/Hardcore","Melodic Death Metal",
                       "Black/Death/Progressive Metal","Power Metal",
                       "Black/Death Metal","Deathcore","Melodic Death Metal/Metalcore",
                       "Sludge Metal","Death/Groove Metal",
                       "Melodic Death Metal, Metalcore","Experimental Progressive Metal/Rock",
                       "Deathcore","Grindcore/Avant-garde/Death Metal","Thrash Metal",
                       "Atmospheric Black Metal/Drone","Melodic Black Metal",
                       "Deathcore","Melodic/Progressive Metal",
                       "Thrash Metal/Metalcore","Atmospheric/Post-Black Metal",
                       "Melodic Black Metal","Death Metal","Metalcore/Groove Metal",
                       "Atmospheric/Post-Black Metal/Shoegaze","Doom/Black Metal",
                       "Melodic Death/Black Metal","Industrial Thrash/Death Metal",
                       "Melodic Power Metal",
                       "Melodic Death/Thrash Metal/Metalcore","Heavy/Thrash Metal","Technical Death Metal",
                       "Stoner/Doom Metal/Ambient","Black Metal",
                       "Melodic Death Metal","Death Metal/Crust/Grindcore",
                       "Progressive Heavy Metal/Metalcore","Deathcore","Power/Thrash Metal",
                       "Metalcore","Progressive/Brutal Death Metal",
                       "Depressive Black Metal","Black Metal",
                       "Technical Death Metal/Grindcore","Melodic Death Metal/Metalcore",
                       "Heavy/Stoner/Alternative Metal","Melodic Death Metal",
                       "Technical Deathcore","Melodic Death Metal","Black Metal",
                       "Melodic/Technical Death Metal/Deathcore","Black Metal",
                       "Atmospheric/Post-Black Metal","Melodic Death Metal",
                       "Atmospheric Black Metal","Metalcore/Melodic Death Metal",
                       "Melodic Death Metal","Thrash Metal/Metalcore","Death Metal",
                       "Death Metal/Hardcore","Slam/Brutal Death Metal",
                       "Doom/Death Metal","Death Metal","Melodic Heavy/Gothic Metal",
                       "Black/Death Metal/Hardcore","Deathcore",
                       "Symphonic/Technical Deathcore","Progressive Death Metal","Heavy Metal",
                       "Atmospheric Black Metal, Ambient","Doom/Gothic Metal",
                       "Death/Sludge Metal","Metalcore/Groove Metal",
                       "Doom/Death Metal","Symphonic/Progressive/Gothic Metal",
                       "Black Metal","Symphonic Progressive Metal/Rock",
                       "Southern/Groove Metal","Death Metal","Black Metal",
                       "Technical Death Metal","Melodic Death Metal/Deathcore",
                       "Power/Death Metal","Symphonic/Depressive Black Metal",
                       "Post-Black Metal, Post-Rock/Hardcore","Ambient/Black Metal",
                       "Technical/Brutal Death Metal","Progressive Metal",
                       "Progressive/Thrash Metal","Death/Thrash Metal","Metalcore",
                       "Black Metal","Groove Metal","Deathcore",
                       "Atmospheric Black Metal/Ambient","Black Metal","Black Metal",
                       "Post-Black Metal","Melodic Black Metal",
                       "Sludge/Doom Metal/Post-Rock","Metalcore","Progressive Gothic Metal",
                       "Deathcore","Doom Metal","Progressive/Death Metal","Metalcore",
                       "Symphonic/Melodic Death Metal",
                       "Djent (early); Progressive Metal (later)","Metalcore",
                       "Melodic Death Metal/Metalcore","Progressive Metal",
                       "Melodic Death Metal/Metalcore","Melodic Death Metal","Brutal Death Metal",
                       "Doom Metal","Progressive Metalcore","Metalcore",
                       "Melodic Death Metal/Metalcore","Black/Death Metal",
                       "Melodic Death Metal","Black/Death Metal","Funeral Doom Metal",
                       "Gothic/Doom/Death Metal","Melodic Death Metal",
                       "Heavy/Power Metal, Hard Rock","Progressive/Technical Death Metal",
                       "Atmospheric Sludge/Post-Metal/Rock",
                       "Death Metal/Deathcore","Doom/Death Metal","Melodic Death/Thrash Metal",
                       "Technical Thrash/Death Metal","Heavy Metal",
                       "Progressive Gothic/Industrial Metal","Gothic Metal","Death Metal",
                       "Experimental Doom/Death Metal",
                       "Technical Death Metal/Goregrind","Post-Metal","Death Metal/Grindcore",
                       "Death/Thrash Metal; Metalcore","Experimental Death Metal",
                       "Symphonic Metal/Rock","Brutal Death Metal",
                       "Progressive Death Metal","Southern Metal/Rock",
                       "Death/Thrash Metal","Melodic Death Metal","Progressive Metal",
                       "Black/Doom Metal","Deathcore/Metalcore","Folk Metal",
                       "Melodic Death Metal/Deathcore","Groove/Death Metal",
                       "Death Metal","Heavy Metal","Industrial/Groove/Death Metal",
                       "Melodic Death Metal/Metalcore",
                       "Melodic Death Metal/Metalcore","Thrash Metal/Hardcore","Black Metal",
                       "Depressive Black Metal/Rock","Doom Metal/Psychedelic Rock",
                       "Power/Doom Metal","Melodic Death/Thrash Metal",
                       "Thrash/Groove Metal","Sludge/Doom Metal","Southern/Sludge/Heavy Metal",
                       "Atmospheric Black Metal","Blackened Doom/Death Metal",
                       "Metalcore","Death/Thrash/Black/Groove Metal",
                       "Brutal Death Metal","Doom/Gothic Metal",
                       "Progressive Death Metal","Grindcore/Metalcore","Metalcore/Death Metal",
                       "Death/Groove Metal","Doom/Groove Metal",
                       "Melodic Death Metal/Metalcore","Melodic Death Metal/Metalcore",
                       "Black Metal","Melodic Black Metal","Deathcore",
                       "Black/Sludge Metal","Melodic Death Metal","Deathcore",
                       "Melodic Death Metal","Metalcore","Doom/Death Metal, Post-Rock",
                       "Heavy Metal","Industrial Death Metal","Metalcore",
                       "Progressive Metal","NWOBHM","Metalcore/Deathcore",
                       "Heavy Metal","Death Metal","Death Metal/Grindcore",
                       "Progressive Metal/Hard Rock","Raw Black Metal",
                       "Progressive/Alternative Metal","Heavy Metal","Melodic/Progressive Metal",
                       "Progressive Metal","Blackened Thrash Metal",
                       "Black Metal","Power/Thrash Metal","Speed Metal","Deathcore",
                       "Groove/Thrash Metal","Heavy Metal",
                       "Thrash Metal/Hardcore","Heavy Metal","Thrash/Death/Black Metal",
                       "Heavy/Thrash Metal","Groove/Sludge Metal","Heavy Metal",
                       "Drone/Doom Metal","Melodic Death Metal/Deathcore",
                       "Thrash Metal/Crustcore","Thrash Metal/Crossover","Thrash Metal",
                       "Black Metal/Ambient","Black Metal","Heavy Metal",
                       "Heavy/Power Metal","Black/Death Metal","Power Metal",
                       "Heavy Metal","Heavy Metal","Heavy/Thrash/Speed Metal",
                       "Sludge/Doom Metal","Death/Thrash Metal",
                       "Thrash/Heavy Metal/RAC","Epic Doom Metal","Thrash Metal/Crossover",
                       "Black Metal","Melodic Death/Black/Industrial Metal",
                       "Heavy Metal/Hard Rock",
                       "Heavy/Thrash Metal (early); Groove/Nu-Metal (later)","Industrial Metal","Black Metal",
                       "Thrash Metal","Thrash Metal",
                       "Raw/Atmospheric Black Metal/Dark Ambient","Thrash Metal","Death Metal",
                       "Black/Heavy Metal","Atmospheric/Depressive Black Metal",
                       "Heavy Metal","Thrash Metal","Speed/Heavy Metal",
                       "Black/Thrash Metal/Hardcore Punk","Black Metal",
                       "Progressive Metal","Black Metal/Ambient","Heavy/Power Metal",
                       "Experimental Black/Death Metal","Black Metal",
                       "Death/Thrash Metal","Gothic Metal","Heavy Metal/Hard Rock",
                       "Melodic Progressive Metal","Death 'n' Roll","Melodic Black Metal",
                       "Melodic Heavy Metal/Hard Rock","Progressive Metal",
                       "Melodic Heavy Metal","Thrash Metal/Metalcore",
                       "Black Metal","Death Metal","Technical Brutal Death Metal",
                       "Atmospheric Death Metal","Funeral Doom Metal",
                       "Sludge Metal","Black Metal/Punk",
                       "Avant-garde Progressive/Doom Metal","Atmospheric Black Metal","Black Metal",
                       "Dark Ambient","Progressive Death Metal","Doom/Death Metal",
                       "Black Metal","Gothic/Symphonic Metal","Black/Thrash Metal",
                       "Funeral Doom Metal","Black Metal","Black Metal/Punk",
                       "Experimental/Drone/Doom Metal","Death/Groove Metal",
                       "Black Metal","Heavy Metal with Punk influences",
                       "Atmospheric Black Metal","Black Metal","Black Metal",
                       "Heavy Metal","Death/Thrash Metal","Death/Thrash Metal",
                       "Black Metal","Atmospheric Sludge Metal","Raw Black Metal",
                       "Black Metal","Avant-garde Doom Metal","Black Metal",
                       "Heavy Metal","Progressive Metal/Rock",
                       "Death/Thrash Metal","Heavy Metal/Hard Rock",
                       "Slam/Brutal Death Metal/Deathcore","Heavy Metal","Black Metal",
                       "Heavy/Power Metal","Experimental Black/Doom Metal","Black Metal",
                       "Raw Black Metal","Black Metal","Heavy Metal","Black Metal",
                       "Black Metal","Atmospheric/Avant-garde Black Metal",
                       "Experimental Ambient Black Metal","Funeral Doom Metal",
                       "Stoner Metal/Rock, Doom Metal","Death/Thrash Metal",
                       "Black Metal","Black Metal/Ambient","Gothic/Power Metal",
                       "Melodic/Gothic Metal","Industrial/Groove Metal",
                       "Death Metal","Gothic Metal","Symphonic Metal",
                       "Black Metal","Black Metal","Black/Folk Metal","Black Metal",
                       "Death Metal","Death/Thrash Metal","Death Metal/Grindcore",
                       "Sludge/Post-Metal","Metalcore/Deathcore",
                       "Brutal Death Metal","Deathcore","Thrash Metal","Deathcore",
                       "Death Metal","Black/Death Metal","Thrash/Death Metal",
                       "Thrash/Speed Metal","Thrash Metal","Black Metal",
                       "Heavy Metal/Hard Rock","Blackened Thrash Metal","Death Metal",
                       "Thrash/Death Metal","Heavy/Speed Metal",
                       "Black Metal/Ambient","Death Metal","Progressive/Death Metal",
                       "Death Metal","Black/Thrash Metal","Black/Death Metal",
                       "Heavy Metal","Blackened Thrash Metal","Death Metal",
                       "Symphonic Metal","Black Metal","Death Metal",
                       "Heavy/Thrash Metal","Death Metal","Black/Death Metal",
                       "Melodic Groove/Death Metal","Death Metal","Melodic Black Metal",
                       "Thrash/Groove Metal","Death Metal","Black Metal",
                       "Black Metal","Black/Death Metal","Black Metal",
                       "Atmospheric/Raw Black Metal","Death Metal","Death Metal"),
            Status = c("Status","Split-up",
                       "Split-up","Active","Active","Active","Active","Active",
                       "Active","Active","Active","Active","Active","Split-up",
                       "Active","Changed name","Split-up","Active",
                       "Split-up","Split-up","Active","Active","Active","Split-up",
                       "Split-up","Split-up","Split-up","Active","Active",
                       "Active","Split-up","Split-up","Active","Unknown",
                       "Active","Split-up","Active","Active","Split-up",
                       "Active","Active","Active","Split-up","Active","Active",
                       "Unknown","Unknown","Active","Split-up","Active",
                       "Active","Active","Active","Changed name","Unknown",
                       "Active","Split-up","Unknown","On hold","Active",
                       "Split-up","Split-up","Unknown","Changed name","Split-up",
                       "Split-up","Active","Active","Changed name","On hold",
                       "Split-up","Active","Split-up","Unknown","Active",
                       "Split-up","On hold","Active","Active","Active",
                       "Active","Changed name","Active","Active","Active",
                       "Active","Split-up","Active","Active","Split-up",
                       "Split-up","Split-up","Split-up","Split-up","Split-up",
                       "Active","Active","Active","Active","Split-up","Active",
                       "Split-up","Split-up","Active","Active","Split-up",
                       "Active","Split-up","Active","Active","Active",
                       "Split-up","On hold","Active","Split-up","Active","Active",
                       "Active","Active","Active","Split-up","Split-up",
                       "Active","Active","Split-up","Active","Active",
                       "Split-up","Active","Unknown","Split-up","Split-up",
                       "Split-up","Active","Split-up","Active","Split-up",
                       "Unknown","Active","Active","Active","Split-up","Active",
                       "Active","Split-up","Split-up","Unknown","Split-up",
                       "Unknown","Active","Split-up","Unknown","Split-up",
                       "Active","Changed name","Split-up","Unknown","Active",
                       "Active","Active","Active","Active","Active",
                       "Split-up","Split-up","Active","Active","Split-up","Active",
                       "Unknown","Active","Split-up","Active","Active",
                       "Active","Unknown","Active","Active","Active",
                       "Changed name","Active","Active","Active","Split-up",
                       "Active","Active","Unknown","Active","Active","Split-up",
                       "Active","Split-up","Active","Active","Active",
                       "Active","Active","Active","Split-up","Active","Split-up",
                       "Active","Active","Split-up","Active","Active",
                       "Split-up","Split-up","Active","Unknown","Unknown",
                       "Active","Active","Active","Changed name","Active",
                       "Split-up","Active","Split-up","Unknown","Active","Active",
                       "Changed name","Active","Active","Active",
                       "Split-up","Active","Split-up","Split-up","Active","Active",
                       "Active","Unknown","Active","Active","Active",
                       "Active","Changed name","Active","Active","Active",
                       "Active","Active","Active","Split-up","Active","On hold",
                       "Active","Active","Active","Unknown","Active",
                       "Unknown","Changed name","Active","Split-up","Split-up",
                       "Split-up","Active","Unknown","Active","Active",
                       "Active","Active","On hold","Active","Split-up","Unknown",
                       "Active","Active","Active","Active","Unknown",
                       "Split-up","Split-up","Split-up","Split-up","Unknown",
                       "Split-up","Changed name","Unknown","Active","On hold",
                       "Active","Active","Active","Unknown","On hold",
                       "Active","Active","Split-up","Unknown","Unknown","On hold",
                       "Unknown","Split-up","Split-up","On hold",
                       "Split-up","Split-up","Active","Active","Active","Active",
                       "Split-up","Active","Split-up","Unknown","Unknown",
                       "Active","Changed name","Active","Unknown",
                       "Changed name","Split-up","Active","Unknown","Active","Split-up",
                       "Split-up","Split-up","Active","Split-up",
                       "Changed name","Changed name","Unknown","Split-up","Split-up",
                       "Active","Active","Split-up","Active","Active",
                       "Active","Active","Split-up","Unknown","Split-up",
                       "On hold","Active","Active","Split-up","Split-up","On hold",
                       "Active","Active","Changed name","Active","Unknown",
                       "Active","Changed name","Unknown","Split-up",
                       "Active","Active","Split-up","Active","Split-up","Active",
                       "Active","Split-up","Active","Active","Split-up",
                       "Unknown","Active","Active","Active","Changed name",
                       "Active","Unknown","Changed name","Active","Unknown",
                       "Active","Active","Unknown","Active","Split-up",
                       "Split-up","Split-up","Active","Unknown","Active",
                       "Unknown","Active","Active","Unknown","Active","Split-up",
                       "Active","Active","Active","Unknown","Active",
                       "Split-up","Split-up","Active","Active","Active","Active",
                       "Split-up","Unknown","Active","Unknown","Unknown",
                       "On hold","Active","Active","Active","Split-up",
                       "Split-up","Split-up","Active","Split-up","Active",
                       "Active","Active","Split-up","Active","Active","Split-up",
                       "Active","Active","Active","Active","Active",
                       "Active","Unknown","Active","Active","Active","Active",
                       "Active","On hold","Active","Active","Active","Active",
                       "Active","Active","Active","Changed name",
                       "Split-up","On hold","Unknown","Active","Active","Unknown",
                       "Active","Active","Split-up","Split-up","Active",
                       "Split-up","Split-up","Active","Active","Active",
                       "Active","Changed name","Active","Active","Split-up",
                       "Split-up","Split-up","Active","Unknown","Active","Active",
                       "Active","Active","Active","Unknown","Split-up",
                       "Unknown","Split-up","Changed name","Active","Split-up",
                       "Changed name","Active","Active","Unknown",
                       "Split-up","On hold","Split-up","Active","On hold",
                       "Split-up","Changed name","Active","Active","Changed name",
                       "Split-up","Changed name","Active","Changed name",
                       "Split-up","Changed name")
)
